import './globals.css';
import { Roboto } from 'next/font/google';
import Header from './header';

const font = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  preload: true,
});

export const metadata = {
  title: 'ConfidentialEngine - Integrator Console',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ja'>
      <body className={font.className + ' bg-white text-gray-800'}>
        <Header />
        {children}
      </body>
    </html>
  );
}
